# Generated by Django 5.1.7 on 2025-03-24 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField()),
                ('imagem', models.URLField(blank=True, null=True)),
                ('preco_original', models.TextField(blank=True, null=True)),
                ('preco', models.TextField(blank=True, null=True)),
                ('parcelamento', models.TextField(blank=True, null=True)),
                ('desconto', models.TextField(blank=True, null=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('tipo_entrega', models.TextField(blank=True, null=True)),
                ('frete_gratis', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
