# Generated by Django 5.1.7 on 2025-03-24 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busca', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='desconto',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='frete_gratis',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='imagem',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='nome',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='produto',
            name='parcelamento',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='preco',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='preco_original',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='tipo_entrega',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
